---
# Gather IP facts from ipify.org
- name: get my public IP
  ipify_facts:
  retries: 3

- name: set internal IP
  set_fact:
    host_internal_ip: "{{ ip_address | default('ansible_default_ipv4.address') }}"

# TODO: enable this for future GCE support in the playbooks
# - name: set public IP
#   set_fact:
#     host_public_ip: "{{ ipify_public_ip }}"
#   when: GCE

- name: set public IP
  set_fact:
    host_public_ip: "{{ ip_address | default('host_internal_ip') }}"
  # when: not GCE   temp_dir: "{{docker_temp_dir | default('C:/Windows/Temp')}}"

- name: set interface name
  set_fact:
    interface_name: "{{ interface_alias | default('ansible_default_ipv4.alias') }}"

- name: set interface gateway
  set_fact:
    interface_gateway: "{{ gateway | default('ansible_default_ipv4.gateway') }}"

- name: set gateway next hop
  set_fact:
    gateway_next_hop: "{{ gateway | default('ansible_default_ipv4.gateway') }}"

- debug: var=ansible_all_ipv4_addresses
- debug: var=host_internal_ip
- debug: var=host_public_ip
- debug: var=gateway_next_hop

